In [1]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

**Data Analysis**

In [3]:
ddf = pd.read_csv('/content/diabetes.csv')

In [4]:
ddf.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [5]:
ddf.shape

(768, 9)

Data Describe


In [6]:
ddf.describe()

Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [7]:
ddf['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

0 --- > Non - Diabetic

1 --- > Diabetic


In [8]:
ddf.groupby('Outcome').mean()

Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...                                     
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

In [69]:
# X will be without outcome column
# Y will be outcome column

X = ddf.drop(columns = "Outcome",axis = 1)
Y = ddf['Outcome']


Standarized Data

In [70]:
scaler = StandardScaler()

In [71]:
scaler.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [72]:
X = scaler.fit_transform(X)


In [73]:
print(X)
print(Y)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


Training and Testing

In [74]:
X_train , X_test ,Y_train , Y_test = train_test_split(X,Y,test_size = 0.2,stratify = Y,random_state = 2)

In [75]:
  print(X.shape,X_train.shape,X_test.shape)

(768, 8) (614, 8) (154, 8)


In [76]:
print(Y.shape,Y_train.shape,Y_test.shape)

(768,) (614,) (154,)


Classifier

In [77]:
classifier = svm.SVC(kernel="linear")

In [78]:
classifier.fit(X_train,Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

Evaluation
Accuracy

In [79]:
X_train_prediction = classifier.predict(X_train)
X_train_accuracy = accuracy_score(X_train_prediction,Y_train)

In [80]:
X_test_prediction = classifier.predict(X_test)
X_test_accuracy = accuracy_score(X_test_prediction,Y_test)

In [81]:
print("Accuracy Score of Training Data : ",X_train_accuracy)
print("Accuracy Score of Test Data : ",X_test_accuracy)

Accuracy Score of Training Data :  0.7866449511400652
Accuracy Score of Test Data :  0.7727272727272727


Input Data


In [98]:
input_data = (8,176,90,34,300,33.7,0.467,58)

arr = np.asarray(input_data)

In [99]:
arr


array([  8.   , 176.   ,  90.   ,  34.   , 300.   ,  33.7  ,   0.467,
        58.   ])

In [100]:
reshape_arr = arr.reshape(1,-1)

In [101]:
reshape_arr

array([[  8.   , 176.   ,  90.   ,  34.   , 300.   ,  33.7  ,   0.467,
         58.   ]])

In [102]:
std_data = scaler.transform(reshape_arr)

In [103]:
std_data
prediction = classifier.predict(std_data)

In [104]:
prediction

array([1])

In [104]:
# 